let blog_data=[
    {
        "title":"哈利波特",
        "author":"曹烨",
        "date":"2018-06-09",
        "content":"哈利波特电影真好看嗷",
        "avatar":"/static/images/test/avatar.svg"
    },
    {
        "title":"毛焦火辣",
        "author":"Ann",
        "date":"2018-06-10",
        "content":"毛焦火辣真好吃嗷",
        "avatar":"/static/images/test/avatar.svg"
    },
    {
        "title":"Switch",
        "author":"David",
        "date":"2018-08-25",
        "content":"Switch真好玩嗷",
        "avatar":"/static/images/test/avatar.svg"
    },
    {
        "title":"赛博朋克2077",
        "author":"Sky",
        "date":"2018-08-02",
        "content":"赛博朋克2077牛逼嗷",
        "avatar":"/static/images/test/avatar.svg"
    },
    {
        "title":"回家",
        "author":"Tony",
        "date":"2018-09-01",
        "content":"把球给我，我要回家",
        "avatar":"/static/images/test/avatar.svg"
    }
];
export default {blog_data};